dir: "{{.InterfaceDir}}"
filename: "mocks_test.go"
inpackage: true
template: testify
packages:
  spotinfo/internal/spot:
    interfaces:
      advisorProvider:
      pricingProvider:
      scoreProvider:
      awsAPIProvider:
  spotinfo/cmd/spotinfo:
    interfaces:
      spotClient:
  spotinfo/internal/mcp:
    interfaces:
      spotClient: