name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Get version
      id: version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        # Add 'v' prefix if not present for release name
        if [[ $TAG_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
          RELEASE_VERSION="v${TAG_NAME}"
        else
          RELEASE_VERSION="${TAG_NAME}"
        fi
        echo "VERSION=${TAG_NAME}" >> $GITHUB_OUTPUT
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
      
    - name: Update embedded data
      run: make update-data update-price
      
    - name: Build release binaries
      run: make release
      
    - name: Create release
      run: |
        gh release create ${{ steps.version.outputs.VERSION }} \
          --title "${{ steps.version.outputs.RELEASE_VERSION }}" \
          --generate-notes \
          .bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}