name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        
    - name: Get version
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Update embedded data
      run: make update-data update-price
      
    - name: Build release binaries
      run: make release
      
    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        name: Release ${{ steps.version.outputs.VERSION }}
        draft: false
        prerelease: false
        files: |
          .bin/*
        body: |
          ## Changes
          
          Release ${{ steps.version.outputs.VERSION }}
          
          ### Downloads
          
          - **Linux AMD64**: `spotinfo_linux_amd64`
          - **Linux ARM64**: `spotinfo_linux_arm64`
          - **macOS AMD64**: `spotinfo_darwin_amd64`
          - **macOS ARM64**: `spotinfo_darwin_arm64`
          - **Windows AMD64**: `spotinfo_windows_amd64`
          
          ### Installation
          
          Download the appropriate binary for your platform and make it executable:
          
          ```bash
          chmod +x spotinfo_*
          ./spotinfo_* --help
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}