name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
      - '[0-9]+.[0-9]+.[0-9]+*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        
    - name: Get version
      id: version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        # Add 'v' prefix if not present for release name
        if [[ $TAG_NAME =~ ^[0-9]+\.[0-9]+\.[0-9]+ ]]; then
          RELEASE_VERSION="v${TAG_NAME}"
        else
          RELEASE_VERSION="${TAG_NAME}"
        fi
        echo "VERSION=${TAG_NAME}" >> $GITHUB_OUTPUT
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
      
    - name: Update embedded data
      run: make update-data update-price
      
    - name: Build release binaries
      run: make release
      
    - name: Create release
      run: |
        gh release create ${{ steps.version.outputs.VERSION }} \
          --title "Release ${{ steps.version.outputs.RELEASE_VERSION }}" \
          --notes-file <(cat <<'EOF'
        ## Changes
        
        Release ${{ steps.version.outputs.RELEASE_VERSION }}
        
        ### Downloads
        
        - **Linux AMD64**: `spotinfo_linux_amd64`
        - **Linux ARM64**: `spotinfo_linux_arm64`
        - **macOS AMD64**: `spotinfo_darwin_amd64`
        - **macOS ARM64**: `spotinfo_darwin_arm64`
        - **Windows AMD64**: `spotinfo_windows_amd64`
        
        ### Installation
        
        Download the appropriate binary for your platform and make it executable:
        
        ```bash
        chmod +x spotinfo_*
        ./spotinfo_* --help
        ```
        EOF
        ) \
          .bin/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}